// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import ChartController from "./chart_controller.js"
application.register("chart", ChartController)

import ProjectController from "./project_controller.js"
application.register("project", ProjectController)

import ResetFormController from "./reset_form_controller.js"
application.register("reset-form", ResetFormController)

import SingleProjectController from "./single_project_controller.js"
application.register("single-project", SingleProjectController)

import ToggleFormController from "./toggle_form_controller.js"
application.register("toggle-form", ToggleFormController)

import UserController from "./user_controller.js"
application.register("user", UserController)

import UserSetController from "./user_set_controller.js"
application.register("user-set", UserSetController)

import VoteFormController from "./vote_form_controller.js"
application.register("vote-form", VoteFormController)
