// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import ProjectController from "./project_controller.js"
application.register("project", ProjectController)

import UserController from "./user_controller.js"
application.register("user", UserController)
